import React from "react";

export const flashcardCategories = [
  {
    name: "99 Common Spanish Words",
    description: "99 most common spanish words",
    words: [
      { spanWord: "el", engTranslation: "the" },
      { spanWord: "de", engTranslation: "of" },
      { spanWord: "que", engTranslation: "that" },
      { spanWord: "y", engTranslation: "and" },
      { spanWord: "a", engTranslation: "to" },
      { spanWord: "en", engTranslation: "in" },
      { spanWord: "un", engTranslation: "a/an" },
      { spanWord: "ser", engTranslation: "to be" },
      { spanWord: "se", engTranslation: "self/oneself" },
      { spanWord: "no", engTranslation: "no" },
      { spanWord: "haber", engTranslation: "to have" },
      { spanWord: "por", engTranslation: "for/by" },
      { spanWord: "con", engTranslation: "with" },
      { spanWord: "su", engTranslation: "his/her/their/your" },
      { spanWord: "para", engTranslation: "for/to" },
      { spanWord: "como", engTranslation: "like/as" },
      { spanWord: "estar", engTranslation: "to be" },
      { spanWord: "tener", engTranslation: "to have" },
      { spanWord: "le", engTranslation: "him/her/you (indirect object)" },
      { spanWord: "lo", engTranslation: "him/her/it/you (direct object)" },
      { spanWord: "todo", engTranslation: "all/everything" },
      { spanWord: "pero", engTranslation: "but" },
      { spanWord: "más", engTranslation: "more" },
      { spanWord: "hacer", engTranslation: "to do/make" },
      { spanWord: "o", engTranslation: "or" },
      { spanWord: "poder", engTranslation: "to be able" },
      { spanWord: "decir", engTranslation: "to say/tell" },
      { spanWord: "este", engTranslation: "this" },
      { spanWord: "ir", engTranslation: "to go" },
      { spanWord: "otro", engTranslation: "other/another" },
      { spanWord: "ese", engTranslation: "that" },
      { spanWord: "la", engTranslation: "the" },
      { spanWord: "si", engTranslation: "if" },
      { spanWord: "me", engTranslation: "me/myself" },
      { spanWord: "ya", engTranslation: "already" },
      { spanWord: "ver", engTranslation: "to see" },
      { spanWord: "porque", engTranslation: "because" },
      { spanWord: "dar", engTranslation: "to give" },
      { spanWord: "cuando", engTranslation: "when" },
      { spanWord: "él", engTranslation: "he" },
      { spanWord: "muy", engTranslation: "very" },
      { spanWord: "sin", engTranslation: "without" },
      { spanWord: "vez", engTranslation: "time" },
      { spanWord: "mucho", engTranslation: "much/many/a lot" },
      { spanWord: "saber", engTranslation: "to know (information)" },
      { spanWord: "qué", engTranslation: "what" },
      { spanWord: "sobre", engTranslation: "on/about" },
      { spanWord: "mi", engTranslation: "my" },
      { spanWord: "alguno", engTranslation: "some" },
      { spanWord: "mismo", engTranslation: "same/self" },
      { spanWord: "yo", engTranslation: "I" },
      { spanWord: "también", engTranslation: "also" },
      { spanWord: "hasta", engTranslation: "until" },
      { spanWord: "año", engTranslation: "year" },
      { spanWord: "dos", engTranslation: "two" },
      { spanWord: "querer", engTranslation: "to want/love" },
      { spanWord: "entre", engTranslation: "between/among" },
      { spanWord: "así", engTranslation: "like this/thus" },
      { spanWord: "primero", engTranslation: "first" },
      { spanWord: "desde", engTranslation: "from/since" },
      { spanWord: "grande", engTranslation: "big/large" },
      { spanWord: "eso", engTranslation: "that" },
      { spanWord: "ni", engTranslation: "neither/nor" },
      { spanWord: "nos", engTranslation: "us" },
      { spanWord: "llegar", engTranslation: "to arrive" },
      { spanWord: "pasar", engTranslation: "to pass/spend time" },
      { spanWord: "tiempo", engTranslation: "time/weather" },
      { spanWord: "ella", engTranslation: "she" },
      { spanWord: "sobre", engTranslation: "over/about" },
      { spanWord: "país", engTranslation: "country" },
      { spanWord: "día", engTranslation: "day" },
      { spanWord: "antes", engTranslation: "before" },
      { spanWord: "siempre", engTranslation: "always" },
      { spanWord: "casa", engTranslation: "house/home" },
      { spanWord: "tanto", engTranslation: "so much/so many" },
      { spanWord: "parte", engTranslation: "part" },
      { spanWord: "caso", engTranslation: "case" },
      { spanWord: "poner", engTranslation: "to put/place" },
      { spanWord: "mismo", engTranslation: "same/self" },
      { spanWord: "seguir", engTranslation: "to follow/continue" },
      { spanWord: "manera", engTranslation: "way/manner" },
      { spanWord: "nuevo", engTranslation: "new" },
      { spanWord: "decir", engTranslation: "to say/tell" },
      { spanWord: "parte", engTranslation: "part" },
      { spanWord: "mientras", engTranslation: "while/as long as" },
      { spanWord: "cada", engTranslation: "each/every" },
      { spanWord: "acuerdo", engTranslation: "agreement" },
      { spanWord: "llevar", engTranslation: "to carry/take" },
      { spanWord: "tres", engTranslation: "three" },
      { spanWord: "punto", engTranslation: "point" },
      { spanWord: "hacer", engTranslation: "to do/make" },
      { spanWord: "otro", engTranslation: "other/another" },
      { spanWord: "año", engTranslation: "year" },
      { spanWord: "día", engTranslation: "day" },
      { spanWord: "manera", engTranslation: "way/manner" },
      { spanWord: "entonces", engTranslation: "then/so" },
      { spanWord: "poner", engTranslation: "to put/place" },
      { spanWord: "tanto", engTranslation: "so much/so many" },
      { spanWord: "estado", engTranslation: "state/condition" },
    ],
  },

  {
    name: "20 Spanish Greetings",
    description: "20 most common spanish greetings",
    words: [
      { spanWord: "hola", engTranslation: "hello" },
      { spanWord: "buenos días", engTranslation: "good morning" },
      { spanWord: "buenas tardes", engTranslation: "good afternoon" },
      { spanWord: "buenas noches", engTranslation: "good evening/good night" },
      { spanWord: "¿cómo estás?", engTranslation: "how are you?" },
      { spanWord: "¿qué tal?", engTranslation: "how's it going?" },
      { spanWord: "¿cómo te va?", engTranslation: "how's everything?" },
      { spanWord: "¿qué haces?", engTranslation: "what are you doing?" },
      { spanWord: "¿cómo se llama?", engTranslation: "what's your name?" },
      { spanWord: "mucho gusto", engTranslation: "nice to meet you" },
      { spanWord: "encantado/a", engTranslation: "pleased to meet you" },
      { spanWord: "adiós", engTranslation: "goodbye" },
      { spanWord: "hasta luego", engTranslation: "see you later" },
      { spanWord: "hasta pronto", engTranslation: "see you soon" },
      { spanWord: "nos vemos", engTranslation: "see you" },
      { spanWord: "chao", engTranslation: "bye" },
      { spanWord: "saludos", engTranslation: "greetings" },
      { spanWord: "bienvenido/a", engTranslation: "welcome" },
      { spanWord: "¿y tú?", engTranslation: "and you?" },
      { spanWord: "¿cómo andas?", engTranslation: "how are you?" },
    ],
  },

  {
    name: "30 Spanish Food Words",
    description: "30 common words to do with food in spanish",
    words: [
      { spanWord: "comida", engTranslation: "food" },
      { spanWord: "bebida", engTranslation: "drink" },
      { spanWord: "pan", engTranslation: "bread" },
      { spanWord: "arroz", engTranslation: "rice" },
      { spanWord: "carne", engTranslation: "meat" },
      { spanWord: "pollo", engTranslation: "chicken" },
      { spanWord: "pescado", engTranslation: "fish" },
      { spanWord: "verduras", engTranslation: "vegetables" },
      { spanWord: "frutas", engTranslation: "fruits" },
      { spanWord: "queso", engTranslation: "cheese" },
      { spanWord: "huevo", engTranslation: "egg" },
      { spanWord: "leche", engTranslation: "milk" },
      { spanWord: "aceite", engTranslation: "oil" },
      { spanWord: "sal", engTranslation: "salt" },
      { spanWord: "azúcar", engTranslation: "sugar" },
      { spanWord: "sopa", engTranslation: "soup" },
      { spanWord: "ensalada", engTranslation: "salad" },
      { spanWord: "pastel", engTranslation: "cake" },
      { spanWord: "helado", engTranslation: "ice cream" },
      { spanWord: "panqueques", engTranslation: "pancakes" },
      { spanWord: "tacos", engTranslation: "tacos" },
      { spanWord: "pizza", engTranslation: "pizza" },
      { spanWord: "pasta", engTranslation: "pasta" },
      { spanWord: "cereal", engTranslation: "cereal" },
      { spanWord: "sandwich", engTranslation: "sandwich" },
      { spanWord: "jugo", engTranslation: "juice" },
      { spanWord: "café", engTranslation: "coffee" },
      { spanWord: "té", engTranslation: "tea" },
      { spanWord: "agua", engTranslation: "water" },
      { spanWord: "postre", engTranslation: "dessert" },
    ],
  },

  {
    name: "54 Spanish Number Words",
    description: "54 common number words in Spanish",
    words: [
      { spanWord: "cero", engTranslation: "zero" },
      { spanWord: "uno", engTranslation: "one" },
      { spanWord: "dos", engTranslation: "two" },
      { spanWord: "tres", engTranslation: "three" },
      { spanWord: "cuatro", engTranslation: "four" },
      { spanWord: "cinco", engTranslation: "five" },
      { spanWord: "seis", engTranslation: "six" },
      { spanWord: "siete", engTranslation: "seven" },
      { spanWord: "ocho", engTranslation: "eight" },
      { spanWord: "nueve", engTranslation: "nine" },
      { spanWord: "diez", engTranslation: "ten" },
      { spanWord: "once", engTranslation: "eleven" },
      { spanWord: "doce", engTranslation: "twelve" },
      { spanWord: "trece", engTranslation: "thirteen" },
      { spanWord: "catorce", engTranslation: "fourteen" },
      { spanWord: "quince", engTranslation: "fifteen" },
      { spanWord: "dieciséis", engTranslation: "sixteen" },
      { spanWord: "diecisiete", engTranslation: "seventeen" },
      { spanWord: "dieciocho", engTranslation: "eighteen" },
      { spanWord: "diecinueve", engTranslation: "nineteen" },
      { spanWord: "veinte", engTranslation: "twenty" },
      { spanWord: "veintiuno", engTranslation: "twenty-one" },
      { spanWord: "veintidós", engTranslation: "twenty-two" },
      { spanWord: "veintitrés", engTranslation: "twenty-three" },
      { spanWord: "veinticuatro", engTranslation: "twenty-four" },
      { spanWord: "veinticinco", engTranslation: "twenty-five" },
      { spanWord: "veintiséis", engTranslation: "twenty-six" },
      { spanWord: "veintisiete", engTranslation: "twenty-seven" },
      { spanWord: "veintiocho", engTranslation: "twenty-eight" },
      { spanWord: "veintinueve", engTranslation: "twenty-nine" },
      { spanWord: "treinta", engTranslation: "thirty" },
      { spanWord: "treinta y uno", engTranslation: "thirty-one" },
      { spanWord: "cuarenta", engTranslation: "forty" },
      { spanWord: "cincuenta", engTranslation: "fifty" },
      { spanWord: "sesenta", engTranslation: "sixty" },
      { spanWord: "setenta", engTranslation: "seventy" },
      { spanWord: "ochenta", engTranslation: "eighty" },
      { spanWord: "noventa", engTranslation: "ninety" },
      { spanWord: "cien", engTranslation: "one hundred" },
      { spanWord: "ciento uno", engTranslation: "one hundred one" },
      { spanWord: "doscientos", engTranslation: "two hundred" },
      { spanWord: "trescientos", engTranslation: "three hundred" },
      { spanWord: "cuatrocientos", engTranslation: "four hundred" },
      { spanWord: "quinientos", engTranslation: "five hundred" },
      { spanWord: "seiscientos", engTranslation: "six hundred" },
      { spanWord: "setecientos", engTranslation: "seven hundred" },
      { spanWord: "ochocientos", engTranslation: "eight hundred" },
      { spanWord: "novecientos", engTranslation: "nine hundred" },
      { spanWord: "mil", engTranslation: "thousand" },
      { spanWord: "dos mil", engTranslation: "two thousand" },
      { spanWord: "millón", engTranslation: "million" },
      { spanWord: "millones", engTranslation: "millions" },
      { spanWord: "mil millones", engTranslation: "billion" },
      { spanWord: "billones", engTranslation: "billions" },
    ],
  },

  {
    name: "30 Spanish Navigational Words",
    description: "30 of the most common navigational words in spanish",
    words: [
      { spanWord: "izquierda", engTranslation: "left" },
      { spanWord: "derecha", engTranslation: "right" },
      { spanWord: "adelante", engTranslation: "forward" },
      { spanWord: "atrás", engTranslation: "backward" },
      { spanWord: "arriba", engTranslation: "up" },
      { spanWord: "abajo", engTranslation: "down" },
      { spanWord: "cerca", engTranslation: "near" },
      { spanWord: "lejos", engTranslation: "far" },
      { spanWord: "afuera", engTranslation: "outside" },
      { spanWord: "adentro", engTranslation: "inside" },
      { spanWord: "alrededor", engTranslation: "around" },
      { spanWord: "enfrente", engTranslation: "in front" },
      { spanWord: "atrás", engTranslation: "behind" },
      { spanWord: "a la derecha", engTranslation: "to the right" },
      { spanWord: "a la izquierda", engTranslation: "to the left" },
      { spanWord: "encima", engTranslation: "above/on top" },
      { spanWord: "debajo", engTranslation: "below/under" },
      { spanWord: "entre", engTranslation: "between" },
      { spanWord: "al lado de", engTranslation: "next to" },
      { spanWord: "al final", engTranslation: "at the end" },
      { spanWord: "al principio", engTranslation: "at the beginning" },
      { spanWord: "sigue", engTranslation: "keep going" },
      { spanWord: "pare", engTranslation: "stop" },
      { spanWord: "gire", engTranslation: "turn" },
      { spanWord: "cruce a la izquierda", engTranslation: "turn left" },
      { spanWord: "cruce a la derecha", engTranslation: "turn right" },
      { spanWord: "cruce adelante", engTranslation: "go straight" },
      { spanWord: "cruce atrás", engTranslation: "go back" },
      { spanWord: "sube", engTranslation: "go up" },
      { spanWord: "baja", engTranslation: "go down" },
    ],
  },

  {
    name: "48 Spanish Household Words",
    description: "48 words to describe the house in spanish",
    words: [
      { spanWord: "casa", engTranslation: "house" },
      { spanWord: "puerta", engTranslation: "door" },
      { spanWord: "ventana", engTranslation: "window" },
      { spanWord: "suelo", engTranslation: "floor" },
      { spanWord: "techo", engTranslation: "roof" },
      { spanWord: "pared", engTranslation: "wall" },
      { spanWord: "jardín", engTranslation: "garden" },
      { spanWord: "patio", engTranslation: "patio" },
      { spanWord: "terraza", engTranslation: "terrace" },
      { spanWord: "garaje", engTranslation: "garage" },
      { spanWord: "cocina", engTranslation: "kitchen" },
      { spanWord: "baño", engTranslation: "bathroom" },
      { spanWord: "dormitorio", engTranslation: "bedroom" },
      { spanWord: "sala de estar", engTranslation: "living room" },
      { spanWord: "comedor", engTranslation: "dining room" },
      { spanWord: "escalera", engTranslation: "stairs" },
      { spanWord: "balcón", engTranslation: "balcony" },
      { spanWord: "sótano", engTranslation: "basement" },
      { spanWord: "lavadero", engTranslation: "laundry room" },
      { spanWord: "alfombra", engTranslation: "carpet" },
      { spanWord: "sofá", engTranslation: "sofa" },
      { spanWord: "mesa", engTranslation: "table" },
      { spanWord: "silla", engTranslation: "chair" },
      { spanWord: "estante", engTranslation: "shelf" },
      { spanWord: "armario", engTranslation: "closet" },
      { spanWord: "cajón", engTranslation: "drawer" },
      { spanWord: "cama", engTranslation: "bed" },
      { spanWord: "espejo", engTranslation: "mirror" },
      { spanWord: "lavabo", engTranslation: "sink" },
      { spanWord: "ducha", engTranslation: "shower" },
      { spanWord: "bañera", engTranslation: "bathtub" },
      { spanWord: "toalla", engTranslation: "towel" },
      { spanWord: "cepillo", engTranslation: "brush" },
      { spanWord: "peine", engTranslation: "comb" },
      { spanWord: "inodoro", engTranslation: "toilet" },
      { spanWord: "horno", engTranslation: "oven" },
      { spanWord: "nevera", engTranslation: "fridge" },
      { spanWord: "microondas", engTranslation: "microwave" },
      { spanWord: "fregadero", engTranslation: "sink" },
      { spanWord: "vaso", engTranslation: "glass" },
      { spanWord: "plato", engTranslation: "plate" },
      { spanWord: "cuchillo", engTranslation: "knife" },
      { spanWord: "tenedor", engTranslation: "fork" },
      { spanWord: "cuchara", engTranslation: "spoon" },
      { spanWord: "sartén", engTranslation: "pan" },
      { spanWord: "olla", engTranslation: "pot" },
      { spanWord: "taza", engTranslation: "cup" },
      { spanWord: "aspiradora", engTranslation: "vacuum cleaner" },
    ],
  },

  {
    name: "30 Spanish Clothing Words",
    description: "30 of the most common words for clothing items in spanish",
    words: [
      { spanWord: "camisa", engTranslation: "shirt" },
      { spanWord: "pantalón", engTranslation: "pants" },
      { spanWord: "vestido", engTranslation: "dress" },
      { spanWord: "falda", engTranslation: "skirt" },
      { spanWord: "chaqueta", engTranslation: "jacket" },
      { spanWord: "abrigo", engTranslation: "coat" },
      { spanWord: "suéter", engTranslation: "sweater" },
      { spanWord: "blusa", engTranslation: "blouse" },
      { spanWord: "corbata", engTranslation: "tie" },
      { spanWord: "calcetines", engTranslation: "socks" },
      { spanWord: "zapatos", engTranslation: "shoes" },
      { spanWord: "tenis", engTranslation: "sneakers" },
      { spanWord: "sandalias", engTranslation: "sandals" },
      { spanWord: "sombrero", engTranslation: "hat" },
      { spanWord: "bufanda", engTranslation: "scarf" },
      { spanWord: "guantes", engTranslation: "gloves" },
      { spanWord: "gafas", engTranslation: "glasses" },
      { spanWord: "reloj", engTranslation: "watch" },
      { spanWord: "anillo", engTranslation: "ring" },
      { spanWord: "collar", engTranslation: "necklace" },
      { spanWord: "pulsera", engTranslation: "bracelet" },
      { spanWord: "bolsa", engTranslation: "bag" },
      { spanWord: "cinturón", engTranslation: "belt" },
      { spanWord: "pañuelo", engTranslation: "handkerchief" },
      { spanWord: "ropa interior", engTranslation: "underwear" },
      { spanWord: "pijama", engTranslation: "pajamas" },
      { spanWord: "traje de baño", engTranslation: "swimsuit" },
      { spanWord: "falda", engTranslation: "skirt" },
      { spanWord: "camiseta", engTranslation: "t-shirt" },
      { spanWord: "zapatillas", engTranslation: "slippers" },
    ],
  },

  {
    name: "30 Spanish Descriptive Words",
    description: "30 of the most common words for describing people",
    words: [
      { spanWord: "alto/a", engTranslation: "tall" },
      { spanWord: "bajo/a", engTranslation: "short" },
      { spanWord: "delgado/a", engTranslation: "slim/thin" },
      { spanWord: "gordo/a", engTranslation: "fat" },
      { spanWord: "joven", engTranslation: "young" },
      { spanWord: "viejo/a", engTranslation: "old" },
      { spanWord: "guapo/a", engTranslation: "handsome/beautiful" },
      { spanWord: "feo/a", engTranslation: "ugly" },
      { spanWord: "moreno/a", engTranslation: "brunette/dark-skinned" },
      { spanWord: "rubio/a", engTranslation: "blonde" },
      { spanWord: "pelirrojo/a", engTranslation: "red-haired" },
      { spanWord: "amable", engTranslation: "kind" },
      { spanWord: "malo/a", engTranslation: "bad" },
      { spanWord: "bueno/a", engTranslation: "good" },
      { spanWord: "inteligente", engTranslation: "intelligent" },
      { spanWord: "tonto/a", engTranslation: "silly/stupid" },
      { spanWord: "divertido/a", engTranslation: "funny" },
      { spanWord: "serio/a", engTranslation: "serious" },
      { spanWord: "trabajador/a", engTranslation: "hardworking" },
      { spanWord: "perezoso/a", engTranslation: "lazy" },
      { spanWord: "honesto/a", engTranslation: "honest" },
      { spanWord: "mentiroso/a", engTranslation: "dishonest/liar" },
      { spanWord: "simpático/a", engTranslation: "friendly/nice" },
      { spanWord: "antipático/a", engTranslation: "unfriendly" },
      { spanWord: "valiente", engTranslation: "brave" },
      { spanWord: "cobarde", engTranslation: "cowardly" },
      { spanWord: "generoso/a", engTranslation: "generous" },
      { spanWord: "egoísta", engTranslation: "selfish" },
      { spanWord: "feliz", engTranslation: "happy" },
      { spanWord: "triste", engTranslation: "sad" },
    ],
  },
];
export default flashcardCategories;
